<?php
/**
 * WhiteLabelApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Australia
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: AU
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * WhiteLabelApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class WhiteLabelApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation auWhiteLabelActiveEmployeeReportGet
     *
     * Active Employees Report
     *
     * @param  int $white_label_id white_label_id (required)
     * @param  string $request_email_addresses  (optional)
     * @param  bool $request_include_inactive_businesses  (optional)
     * @param  \DateTime $request_from_date  (optional)
     * @param  \DateTime $request_to_date  (optional)
     * @param  int $request_location_id  (optional)
     * @param  int $request_employing_entity_id  (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\AuActiveEmployeesModel[]
     */
    public function auWhiteLabelActiveEmployeeReportGet($white_label_id, $request_email_addresses = null, $request_include_inactive_businesses = null, $request_from_date = null, $request_to_date = null, $request_location_id = null, $request_employing_entity_id = null)
    {
        list($response) = $this->auWhiteLabelActiveEmployeeReportGetWithHttpInfo($white_label_id, $request_email_addresses, $request_include_inactive_businesses, $request_from_date, $request_to_date, $request_location_id, $request_employing_entity_id);
        return $response;
    }

    /**
     * Operation auWhiteLabelActiveEmployeeReportGetWithHttpInfo
     *
     * Active Employees Report
     *
     * @param  int $white_label_id (required)
     * @param  string $request_email_addresses  (optional)
     * @param  bool $request_include_inactive_businesses  (optional)
     * @param  \DateTime $request_from_date  (optional)
     * @param  \DateTime $request_to_date  (optional)
     * @param  int $request_location_id  (optional)
     * @param  int $request_employing_entity_id  (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\AuActiveEmployeesModel[], HTTP status code, HTTP response headers (array of strings)
     */
    public function auWhiteLabelActiveEmployeeReportGetWithHttpInfo($white_label_id, $request_email_addresses = null, $request_include_inactive_businesses = null, $request_from_date = null, $request_to_date = null, $request_location_id = null, $request_employing_entity_id = null)
    {
        $returnType = '\Swagger\Client\Model\AuActiveEmployeesModel[]';
        $request = $this->auWhiteLabelActiveEmployeeReportGetRequest($white_label_id, $request_email_addresses, $request_include_inactive_businesses, $request_from_date, $request_to_date, $request_location_id, $request_employing_entity_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\AuActiveEmployeesModel[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation auWhiteLabelActiveEmployeeReportGetAsync
     *
     * Active Employees Report
     *
     * @param  int $white_label_id (required)
     * @param  string $request_email_addresses  (optional)
     * @param  bool $request_include_inactive_businesses  (optional)
     * @param  \DateTime $request_from_date  (optional)
     * @param  \DateTime $request_to_date  (optional)
     * @param  int $request_location_id  (optional)
     * @param  int $request_employing_entity_id  (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function auWhiteLabelActiveEmployeeReportGetAsync($white_label_id, $request_email_addresses = null, $request_include_inactive_businesses = null, $request_from_date = null, $request_to_date = null, $request_location_id = null, $request_employing_entity_id = null)
    {
        return $this->auWhiteLabelActiveEmployeeReportGetAsyncWithHttpInfo($white_label_id, $request_email_addresses, $request_include_inactive_businesses, $request_from_date, $request_to_date, $request_location_id, $request_employing_entity_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation auWhiteLabelActiveEmployeeReportGetAsyncWithHttpInfo
     *
     * Active Employees Report
     *
     * @param  int $white_label_id (required)
     * @param  string $request_email_addresses  (optional)
     * @param  bool $request_include_inactive_businesses  (optional)
     * @param  \DateTime $request_from_date  (optional)
     * @param  \DateTime $request_to_date  (optional)
     * @param  int $request_location_id  (optional)
     * @param  int $request_employing_entity_id  (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function auWhiteLabelActiveEmployeeReportGetAsyncWithHttpInfo($white_label_id, $request_email_addresses = null, $request_include_inactive_businesses = null, $request_from_date = null, $request_to_date = null, $request_location_id = null, $request_employing_entity_id = null)
    {
        $returnType = '\Swagger\Client\Model\AuActiveEmployeesModel[]';
        $request = $this->auWhiteLabelActiveEmployeeReportGetRequest($white_label_id, $request_email_addresses, $request_include_inactive_businesses, $request_from_date, $request_to_date, $request_location_id, $request_employing_entity_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'auWhiteLabelActiveEmployeeReportGet'
     *
     * @param  int $white_label_id (required)
     * @param  string $request_email_addresses  (optional)
     * @param  bool $request_include_inactive_businesses  (optional)
     * @param  \DateTime $request_from_date  (optional)
     * @param  \DateTime $request_to_date  (optional)
     * @param  int $request_location_id  (optional)
     * @param  int $request_employing_entity_id  (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function auWhiteLabelActiveEmployeeReportGetRequest($white_label_id, $request_email_addresses = null, $request_include_inactive_businesses = null, $request_from_date = null, $request_to_date = null, $request_location_id = null, $request_employing_entity_id = null)
    {
        // verify the required parameter 'white_label_id' is set
        if ($white_label_id === null || (is_array($white_label_id) && count($white_label_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $white_label_id when calling auWhiteLabelActiveEmployeeReportGet'
            );
        }

        $resourcePath = '/api/v2/whitelabel/{whiteLabelId}/reports/activeemployees';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($request_email_addresses !== null) {
            $queryParams['request.emailAddresses'] = ObjectSerializer::toQueryValue($request_email_addresses);
        }
        // query params
        if ($request_include_inactive_businesses !== null) {
            $queryParams['request.includeInactiveBusinesses'] = ObjectSerializer::toQueryValue($request_include_inactive_businesses);
        }
        // query params
        if ($request_from_date !== null) {
            $queryParams['request.fromDate'] = ObjectSerializer::toQueryValue($request_from_date);
        }
        // query params
        if ($request_to_date !== null) {
            $queryParams['request.toDate'] = ObjectSerializer::toQueryValue($request_to_date);
        }
        // query params
        if ($request_location_id !== null) {
            $queryParams['request.locationId'] = ObjectSerializer::toQueryValue($request_location_id);
        }
        // query params
        if ($request_employing_entity_id !== null) {
            $queryParams['request.employingEntityId'] = ObjectSerializer::toQueryValue($request_employing_entity_id);
        }

        // path params
        if ($white_label_id !== null) {
            $resourcePath = str_replace(
                '{' . 'whiteLabelId' . '}',
                ObjectSerializer::toPathValue($white_label_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json', 'application/xml', 'text/xml']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json', 'application/xml', 'text/xml'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('apiKey');
        if ($apiKey !== null) {
            $headers['apiKey'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation whiteLabelGet
     *
     * Get White Label by ID
     *
     * @param  int $id id (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\WhiteLabelModel
     */
    public function whiteLabelGet($id)
    {
        list($response) = $this->whiteLabelGetWithHttpInfo($id);
        return $response;
    }

    /**
     * Operation whiteLabelGetWithHttpInfo
     *
     * Get White Label by ID
     *
     * @param  int $id (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\WhiteLabelModel, HTTP status code, HTTP response headers (array of strings)
     */
    public function whiteLabelGetWithHttpInfo($id)
    {
        $returnType = '\Swagger\Client\Model\WhiteLabelModel';
        $request = $this->whiteLabelGetRequest($id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\WhiteLabelModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation whiteLabelGetAsync
     *
     * Get White Label by ID
     *
     * @param  int $id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function whiteLabelGetAsync($id)
    {
        return $this->whiteLabelGetAsyncWithHttpInfo($id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation whiteLabelGetAsyncWithHttpInfo
     *
     * Get White Label by ID
     *
     * @param  int $id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function whiteLabelGetAsyncWithHttpInfo($id)
    {
        $returnType = '\Swagger\Client\Model\WhiteLabelModel';
        $request = $this->whiteLabelGetRequest($id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'whiteLabelGet'
     *
     * @param  int $id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function whiteLabelGetRequest($id)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling whiteLabelGet'
            );
        }

        $resourcePath = '/api/v2/whitelabel/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json', 'application/xml', 'text/xml']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json', 'application/xml', 'text/xml'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('apiKey');
        if ($apiKey !== null) {
            $headers['apiKey'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation whiteLabelGetWhiteLabels
     *
     * List White Labels
     *
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\WhiteLabelModel[]
     */
    public function whiteLabelGetWhiteLabels()
    {
        list($response) = $this->whiteLabelGetWhiteLabelsWithHttpInfo();
        return $response;
    }

    /**
     * Operation whiteLabelGetWhiteLabelsWithHttpInfo
     *
     * List White Labels
     *
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\WhiteLabelModel[], HTTP status code, HTTP response headers (array of strings)
     */
    public function whiteLabelGetWhiteLabelsWithHttpInfo()
    {
        $returnType = '\Swagger\Client\Model\WhiteLabelModel[]';
        $request = $this->whiteLabelGetWhiteLabelsRequest();

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\WhiteLabelModel[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation whiteLabelGetWhiteLabelsAsync
     *
     * List White Labels
     *
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function whiteLabelGetWhiteLabelsAsync()
    {
        return $this->whiteLabelGetWhiteLabelsAsyncWithHttpInfo()
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation whiteLabelGetWhiteLabelsAsyncWithHttpInfo
     *
     * List White Labels
     *
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function whiteLabelGetWhiteLabelsAsyncWithHttpInfo()
    {
        $returnType = '\Swagger\Client\Model\WhiteLabelModel[]';
        $request = $this->whiteLabelGetWhiteLabelsRequest();

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'whiteLabelGetWhiteLabels'
     *
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function whiteLabelGetWhiteLabelsRequest()
    {

        $resourcePath = '/api/v2/whitelabel';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json', 'application/xml', 'text/xml']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json', 'application/xml', 'text/xml'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('apiKey');
        if ($apiKey !== null) {
            $headers['apiKey'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation whiteLabelReportGet
     *
     * Signup Report
     *
     * @param  int $whitelabel_id whitelabel_id (required)
     * @param  string $request_email_addresses  (optional)
     * @param  \DateTime $request_from_date  (optional)
     * @param  \DateTime $request_to_date  (optional)
     * @param  int $request_location_id  (optional)
     * @param  int $request_employing_entity_id  (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\SignupModel[]
     */
    public function whiteLabelReportGet($whitelabel_id, $request_email_addresses = null, $request_from_date = null, $request_to_date = null, $request_location_id = null, $request_employing_entity_id = null)
    {
        list($response) = $this->whiteLabelReportGetWithHttpInfo($whitelabel_id, $request_email_addresses, $request_from_date, $request_to_date, $request_location_id, $request_employing_entity_id);
        return $response;
    }

    /**
     * Operation whiteLabelReportGetWithHttpInfo
     *
     * Signup Report
     *
     * @param  int $whitelabel_id (required)
     * @param  string $request_email_addresses  (optional)
     * @param  \DateTime $request_from_date  (optional)
     * @param  \DateTime $request_to_date  (optional)
     * @param  int $request_location_id  (optional)
     * @param  int $request_employing_entity_id  (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\SignupModel[], HTTP status code, HTTP response headers (array of strings)
     */
    public function whiteLabelReportGetWithHttpInfo($whitelabel_id, $request_email_addresses = null, $request_from_date = null, $request_to_date = null, $request_location_id = null, $request_employing_entity_id = null)
    {
        $returnType = '\Swagger\Client\Model\SignupModel[]';
        $request = $this->whiteLabelReportGetRequest($whitelabel_id, $request_email_addresses, $request_from_date, $request_to_date, $request_location_id, $request_employing_entity_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\SignupModel[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation whiteLabelReportGetAsync
     *
     * Signup Report
     *
     * @param  int $whitelabel_id (required)
     * @param  string $request_email_addresses  (optional)
     * @param  \DateTime $request_from_date  (optional)
     * @param  \DateTime $request_to_date  (optional)
     * @param  int $request_location_id  (optional)
     * @param  int $request_employing_entity_id  (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function whiteLabelReportGetAsync($whitelabel_id, $request_email_addresses = null, $request_from_date = null, $request_to_date = null, $request_location_id = null, $request_employing_entity_id = null)
    {
        return $this->whiteLabelReportGetAsyncWithHttpInfo($whitelabel_id, $request_email_addresses, $request_from_date, $request_to_date, $request_location_id, $request_employing_entity_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation whiteLabelReportGetAsyncWithHttpInfo
     *
     * Signup Report
     *
     * @param  int $whitelabel_id (required)
     * @param  string $request_email_addresses  (optional)
     * @param  \DateTime $request_from_date  (optional)
     * @param  \DateTime $request_to_date  (optional)
     * @param  int $request_location_id  (optional)
     * @param  int $request_employing_entity_id  (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function whiteLabelReportGetAsyncWithHttpInfo($whitelabel_id, $request_email_addresses = null, $request_from_date = null, $request_to_date = null, $request_location_id = null, $request_employing_entity_id = null)
    {
        $returnType = '\Swagger\Client\Model\SignupModel[]';
        $request = $this->whiteLabelReportGetRequest($whitelabel_id, $request_email_addresses, $request_from_date, $request_to_date, $request_location_id, $request_employing_entity_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'whiteLabelReportGet'
     *
     * @param  int $whitelabel_id (required)
     * @param  string $request_email_addresses  (optional)
     * @param  \DateTime $request_from_date  (optional)
     * @param  \DateTime $request_to_date  (optional)
     * @param  int $request_location_id  (optional)
     * @param  int $request_employing_entity_id  (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function whiteLabelReportGetRequest($whitelabel_id, $request_email_addresses = null, $request_from_date = null, $request_to_date = null, $request_location_id = null, $request_employing_entity_id = null)
    {
        // verify the required parameter 'whitelabel_id' is set
        if ($whitelabel_id === null || (is_array($whitelabel_id) && count($whitelabel_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $whitelabel_id when calling whiteLabelReportGet'
            );
        }

        $resourcePath = '/api/v2/whitelabel/{whitelabelId}/reports/signups';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($request_email_addresses !== null) {
            $queryParams['request.emailAddresses'] = ObjectSerializer::toQueryValue($request_email_addresses);
        }
        // query params
        if ($request_from_date !== null) {
            $queryParams['request.fromDate'] = ObjectSerializer::toQueryValue($request_from_date);
        }
        // query params
        if ($request_to_date !== null) {
            $queryParams['request.toDate'] = ObjectSerializer::toQueryValue($request_to_date);
        }
        // query params
        if ($request_location_id !== null) {
            $queryParams['request.locationId'] = ObjectSerializer::toQueryValue($request_location_id);
        }
        // query params
        if ($request_employing_entity_id !== null) {
            $queryParams['request.employingEntityId'] = ObjectSerializer::toQueryValue($request_employing_entity_id);
        }

        // path params
        if ($whitelabel_id !== null) {
            $resourcePath = str_replace(
                '{' . 'whitelabelId' . '}',
                ObjectSerializer::toPathValue($whitelabel_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json', 'application/xml', 'text/xml']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json', 'application/xml', 'text/xml'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('apiKey');
        if ($apiKey !== null) {
            $headers['apiKey'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
