<?php
/**
 * KioskAccessModel
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Australia
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: AU
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * KioskAccessModel Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class KioskAccessModel implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'KioskAccessModel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'kiosks' => 'int[]',
        'access_type' => 'string',
        'permissions' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'kiosks' => 'int32',
        'access_type' => null,
        'permissions' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'kiosks' => false,
		'access_type' => false,
		'permissions' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'kiosks' => 'kiosks',
        'access_type' => 'accessType',
        'permissions' => 'permissions'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'kiosks' => 'setKiosks',
        'access_type' => 'setAccessType',
        'permissions' => 'setPermissions'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'kiosks' => 'getKiosks',
        'access_type' => 'getAccessType',
        'permissions' => 'getPermissions'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const ACCESS_TYPE_NONE = 'None';
    public const ACCESS_TYPE_ALL_KIOSKS = 'AllKiosks';
    public const ACCESS_TYPE_SPECIFIC_KIOSKS = 'SpecificKiosks';
    public const PERMISSIONS_APPROVE_TIMESHEETS = 'ApproveTimesheets';
    public const PERMISSIONS_APPROVE_LEAVE_REQUESTS = 'ApproveLeaveRequests';
    public const PERMISSIONS_CREATE_TIMESHEETS = 'CreateTimesheets';
    public const PERMISSIONS_CREATE_LEAVE_REQUESTS = 'CreateLeaveRequests';
    public const PERMISSIONS_VIEW_LEAVE_REQUESTS = 'ViewLeaveRequests';
    public const PERMISSIONS_MANAGE_ROSTERS = 'ManageRosters';
    public const PERMISSIONS_VIEW_ROSTERS = 'ViewRosters';
    public const PERMISSIONS_VIEW_SHIFT_COSTS = 'ViewShiftCosts';
    public const PERMISSIONS_VIEW_EXPENSES = 'ViewExpenses';
    public const PERMISSIONS_CREATE_EXPENSES = 'CreateExpenses';
    public const PERMISSIONS_APPROVE_EXPENSES = 'ApproveExpenses';
    public const PERMISSIONS_CREATE_TASKS = 'CreateTasks';
    public const PERMISSIONS_VIEW_EMPLOYEE_DOCUMENTS = 'ViewEmployeeDocuments';
    public const PERMISSIONS_MANAGE_EMPLOYEE_DOCUMENTS = 'ManageEmployeeDocuments';
    public const PERMISSIONS_VIEW_EMPLOYEE_QUALIFICATIONS = 'ViewEmployeeQualifications';
    public const PERMISSIONS_MANAGE_EMPLOYEE_QUALIFICATIONS = 'ManageEmployeeQualifications';
    public const PERMISSIONS_INITIATE_EMPLOYEE_SELF_SETUP = 'InitiateEmployeeSelfSetup';
    public const PERMISSIONS_ADD_EMPLOYEE_FROM_KIOSK = 'AddEmployeeFromKiosk';
    public const PERMISSIONS_VIEW_EMPLOYEE_DETAILS = 'ViewEmployeeDetails';
    public const PERMISSIONS_EDIT_BASIC_EMPLOYEE_DETAILS = 'EditBasicEmployeeDetails';
    public const PERMISSIONS_EDIT_ALL_EMPLOYEE_DETAILS = 'EditAllEmployeeDetails';
    public const PERMISSIONS_VIEW_TIMESHEET_REPORTS = 'ViewTimesheetReports';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAccessTypeAllowableValues()
    {
        return [
            self::ACCESS_TYPE_NONE,
            self::ACCESS_TYPE_ALL_KIOSKS,
            self::ACCESS_TYPE_SPECIFIC_KIOSKS,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPermissionsAllowableValues()
    {
        return [
            self::PERMISSIONS_APPROVE_TIMESHEETS,
            self::PERMISSIONS_APPROVE_LEAVE_REQUESTS,
            self::PERMISSIONS_CREATE_TIMESHEETS,
            self::PERMISSIONS_CREATE_LEAVE_REQUESTS,
            self::PERMISSIONS_VIEW_LEAVE_REQUESTS,
            self::PERMISSIONS_MANAGE_ROSTERS,
            self::PERMISSIONS_VIEW_ROSTERS,
            self::PERMISSIONS_VIEW_SHIFT_COSTS,
            self::PERMISSIONS_VIEW_EXPENSES,
            self::PERMISSIONS_CREATE_EXPENSES,
            self::PERMISSIONS_APPROVE_EXPENSES,
            self::PERMISSIONS_CREATE_TASKS,
            self::PERMISSIONS_VIEW_EMPLOYEE_DOCUMENTS,
            self::PERMISSIONS_MANAGE_EMPLOYEE_DOCUMENTS,
            self::PERMISSIONS_VIEW_EMPLOYEE_QUALIFICATIONS,
            self::PERMISSIONS_MANAGE_EMPLOYEE_QUALIFICATIONS,
            self::PERMISSIONS_INITIATE_EMPLOYEE_SELF_SETUP,
            self::PERMISSIONS_ADD_EMPLOYEE_FROM_KIOSK,
            self::PERMISSIONS_VIEW_EMPLOYEE_DETAILS,
            self::PERMISSIONS_EDIT_BASIC_EMPLOYEE_DETAILS,
            self::PERMISSIONS_EDIT_ALL_EMPLOYEE_DETAILS,
            self::PERMISSIONS_VIEW_TIMESHEET_REPORTS,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('kiosks', $data ?? [], null);
        $this->setIfExists('access_type', $data ?? [], null);
        $this->setIfExists('permissions', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getAccessTypeAllowableValues();
        if (!is_null($this->container['access_type']) && !in_array($this->container['access_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'access_type', must be one of '%s'",
                $this->container['access_type'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getPermissionsAllowableValues();
        if (!is_null($this->container['permissions']) && !in_array($this->container['permissions'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'permissions', must be one of '%s'",
                $this->container['permissions'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets kiosks
     *
     * @return int[]|null
     */
    public function getKiosks()
    {
        return $this->container['kiosks'];
    }

    /**
     * Sets kiosks
     *
     * @param int[]|null $kiosks 
     *
     * @return self
     */
    public function setKiosks($kiosks)
    {
        if (is_null($kiosks)) {
            throw new \InvalidArgumentException('non-nullable kiosks cannot be null');
        }
        $this->container['kiosks'] = $kiosks;

        return $this;
    }

    /**
     * Gets access_type
     *
     * @return string|null
     */
    public function getAccessType()
    {
        return $this->container['access_type'];
    }

    /**
     * Sets access_type
     *
     * @param string|null $access_type 
     *
     * @return self
     */
    public function setAccessType($access_type)
    {
        if (is_null($access_type)) {
            throw new \InvalidArgumentException('non-nullable access_type cannot be null');
        }
        $allowedValues = $this->getAccessTypeAllowableValues();
        if (!in_array($access_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'access_type', must be one of '%s'",
                    $access_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['access_type'] = $access_type;

        return $this;
    }

    /**
     * Gets permissions
     *
     * @return string|null
     */
    public function getPermissions()
    {
        return $this->container['permissions'];
    }

    /**
     * Sets permissions
     *
     * @param string|null $permissions 
     *
     * @return self
     */
    public function setPermissions($permissions)
    {
        if (is_null($permissions)) {
            throw new \InvalidArgumentException('non-nullable permissions cannot be null');
        }
        $allowedValues = $this->getPermissionsAllowableValues();
        if (!in_array($permissions, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'permissions', must be one of '%s'",
                    $permissions,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['permissions'] = $permissions;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


